### ISSUE TITLE
"Conditional binary operator expected" 

### ISSUE THREAD

**Issue by volcs0** [dougy147/scitopdf#1]
Mac OS 12.0.1

```
/usr/local/bin/scitopdf: line 21: conditional binary operator expected
/usr/local/bin/scitopdf: line 21: syntax error near `READER'
/usr/local/bin/scitopdf: line 21: `[[ -v READER ]] || \'
```

This happens just running the script - with or without options.

**Comment by dougy147** [comment]
Out of curiosity, could you provide your bash version ? 

`bash --version`

Because it could be a bash compatibility problem.
According to [sources](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba) I've come across, macOS is running a decade old version of bash.
If that's the problem, one would have to work on retrocompatibility (which I don't plan to).
Maybe you could try installing a newer version of bash :
- [Upgrading bash on macOS](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)
- [How to update bash version on macOS](https://www.dev2qa.com/how-to-update-bash-version-on-macos/)

Moreover, since Catalina (10.15), macOS default shell is zsh ([which might cause compatibility problem too](https://blacksamsays.com/post/bash-on-mac/)).
To test that, you can :
- [Download](https://github.com/dougy147/scitopdf/blob/master/bin/scitopdf) the script alone (**no** sudo make install)
- And follow [those instructions](https://cordero.me/macos-shebang-for-bash-scripts/)

As I have no way to work on this script from macOS perspective, I let that issue open.
If some mac user can help, or create a new branch dedicated to macOS compatibility, that would be great.

**Comment by volcs0** [comment]
Thanks.

I upgraded Bash to the 2020 version - same error.

I tried the direct download and running it as a bash script - same error.

Thanks for the help with this. I'm happy to test further, if it's helpful.

**Comment by volcs0** [comment]
Ok - fixed this problem - forgot to change the version of bash in the
script to /usr/local/bin/bash, so it was using the old one.

There are new errors now - I will try to work through them and post my
results.

**Comment by dougy147** [comment]
After all that time, the [last commit](https://github.com/dougy147/scitopdf/commit/f25212479caa5f73d8ab2c2d76e70871b46468f1) should fix this issue.

To check the existence of variables on old versions of bash needed to change `-v $variable` to `! -z ${variable+x}` in the script. See that [recent post](https://stackoverflow.com/a/75411001) for more infos.

Cheers
