### ISSUE TITLE
search without crossref

### ISSUE THREAD

**Issue by Arznnn** [dougy147/scitopdf#7]
I there the possibility to look up a pdf just on the basis of its title?

When I search for:
`scitopdf "The mirror-neuron system: A Bayesian perspective"`:
>  ▄▀▀░▄▀▀░█░▀█▀░▄▀▄▒█▀▄░█▀▄▒█▀
>  ▄██░▀▄▄░█░▒█▒░▀▄▀░█▀▒▒█▄▀░█▀
> User search not found on Crossref.
> Paper not found.

... no results are found. When I search with the same string/title on google scholar or scihub I find exactly the one paper I want.
Only crossref does not seem to know what I am looking for.

Is there an option to disable crossref for your program?

I am using the Arch AUR version of scitopdf (r157.8d4d2b8-1).

**Comment by dougy147** [comment]
Hi @Arznnn,

Yes it is possible to look up a pdf on the basis of its title.

Sparing details, the problem you encountered is due to characters not URL-encoded in your input (the `:`).
The last commit 8090a3d circumvents the need for URL-encoding, and it should work now.

As of disabling Crossref, there is no option for this because we need it when the user input is neither a DOI or a URL.
